#!/bin/bash

# TODO: this should be replaced with a permission based input
for i in `seq 0 16`; do gpio mode $i out; done
for i in `seq 0 16`; do gpio write $i 0; done

gpio unexportall

IFS=","
for i in $WORKER_LIMITS
do
   eval gpio $i
done

chown -HR root.gpio /sys/class/gpio/*
chmod -R g+w /sys/class/gpio/*

gpio exports

echo "Finished setting GPIO ports..."
